### ISSUE TITLE
media/list doesn't work

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#124]
> Caught exception in MediaWords::Controller::Admin::Media->list "Traceback (most recent call last): File "/home/mediacloud/mediacloud/mediacloud/mediawords/db/result/result.py", line 56, in __execute cursor.execute(*query_args) File "/home/mediacloud/mediacloud/mc-venv/lib/python3.5/site-packages/psycopg2/extras.py", line 120, in execute return super(DictCursor, self).execute(query, vars) TypeError: 'dict' object does not support indexing During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/mediacloud/mediacloud/mediacloud/mediawords/db/handler.py", line 881, in query_paged_hashes return DatabasePages(cursor=self.__db, query=query, page=page, rows_per_page=rows_per_page) File "/home/mediacloud/mediacloud/mediacloud/mediawords/db/pages/pages.py", line 19, in __init__ self.__execute(cursor=cursor, query=query, page=page, rows_per_page=rows_per_page) File "/home/mediacloud/mediacloud/mediacloud/mediawords/db/pages/pages.py", line 40, in __execute rs = DatabaseResult(cursor=cursor, query_args=query_args) File "/home/mediacloud/mediacloud/mediacloud/mediawords/db/result/result.py", line 25, in __init__ self.__execute(cursor=cursor, query_args=query_args, print_warnings=print_warnings) File "/home/mediacloud/mediacloud/mediacloud/mediawords/db/result/result.py", line 94, in __execute 'query': str(query_args), mediawords.db.exceptions.result.McDatabaseResultException: Invalid query (DBD::Pg -> psycopg2 query conversion?): 'dict' object does not support indexing; query: (" select distinct m.media_id as media_id, m.name as name, m.url as url\n from media m\n left join (\n media_tags_map mtm join (\n tags t join tag_sets ts on ( t.tag_sets_id = ts.tag_sets_id) )\n on ( mtm.tags_id = t.tags_id) )\n on (m.media_id = mtm.media_id)\n where (m.name ilike '%superglue%%' or m.url ilike '%superglue%%' or lower(ts.name||':'||t.tag) ilike '%superglue%%')\n order by m.media_id\n LIMIT ( 25 + 1 ) OFFSET 0", {})"

**Comment by pypt** [comment]
Works now I suppose.
