### ISSUE TITLE
time out in python web fetching can crash a topic

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#226]
topic 1864 failed with this error:

multiprocessing.pool.RemoteTraceback:                                                                                           +
 """                                                                                                                             +
 Traceback (most recent call last):                                                                                              +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/urllib3/response.py", line 302, in _error_catcher  +
     yield                                                                                                                       +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/urllib3/response.py", line 384, in read            +
     data = self._fp.read(amt)                                                                                                   +
   File "/usr/lib/python3.5/http/client.py", line 448, in read                                                                   +
     n = self.readinto(b)                                                                                                        +
   File "/usr/lib/python3.5/http/client.py", line 488, in readinto                                                               +
     n = self.fp.readinto(b)                                                                                                     +
   File "/usr/lib/python3.5/socket.py", line 575, in readinto                                                                    +
     return self._sock.recv_into(b)                                                                                              +
 socket.timeout: timed out                                                                                                       +
                                                                                                                                 +
 During handling of the above exception, another exception occurred:                                                             +
                                                                                                                                 +
 Traceback (most recent call last):                                                                                              +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/requests/models.py", line 745, in generate         +
     for chunk in self.raw.stream(chunk_size, decode_content=True):                                                              +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/urllib3/response.py", line 436, in stream          +
     data = self.read(amt=amt, decode_content=decode_content)                                                                    +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/urllib3/response.py", line 401, in read            +
     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)                                                            +
   File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__                                                                 +
     self.gen.throw(type, value, traceback)                                                                                      +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/urllib3/response.py", line 307, in _error_catcher  +
     raise ReadTimeoutError(self._pool, None, 'Read timed out.')                                                                 +
 urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='outbreaknewstoday.com', port=80): Read timed out.                 +
                                                                                                                                 +
 During handling of the above exception, another exception occurred:                                                             +
                                                                                                                                 +
 Traceback (most recent call last):                                                                                              +
   File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker                                                        +
     result = (True, func(*args, **kwds))                                                                                        +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent.py", line 112, in _parallel_get_web_store         +
     response = ua.get_follow_http_html_redirects(url=scheduled_url.url)                                                         +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent.py", line 398, in get_follow_http_html_redirects  +
     response = self.get(url)                                                                                                    +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent.py", line 252, in get                             +
     return self.request(request)                                                                                                +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent.py", line 750, in request                         +
     if requests_response.apparent_encoding is None:                                                                             +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/requests/models.py", line 722, in apparent_encoding+
     return chardet.detect(self.content)['encoding']                                                                             +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/requests/models.py", line 823, in content          +
     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()                                              +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/requests/models.py", line 752, in generate         +
     raise ConnectionError(e)                                                                                                    +
 requests.exceptions.ConnectionError: HTTPConnectionPool(host='outbreaknewstoday.com', port=80): Read timed out.                 +
 """                                                                                                                             +
                                                                                                                                 +
 The above exception was the direct cause of the following exception:                                                            +
                                                                                                                                 +
 Traceback (most recent call last):                                                                                              +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent.py", line 526, in parallel_get                    +
     responses = result.get()                                                                                                    +
   File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get                                                           +
     raise self._value                                                                                                           +
 requests.exceptions.ConnectionError: None: None                                                                                 +

**Comment by pypt** [comment]
Acknowledged. Currently it manages to catch timeouts correctly on connecting to the server but not on reading.

How blocking is this?

**Comment by pypt** [comment]
Probably fixed, please try again, reopen if needed.
