### ISSUE TITLE
Topics 1870 and 1873 break at new Python UserAgent

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#232]
1870:

```
--------------------------------------------------------------------------------------------------------------------------
 Traceback (most recent call last):                                                                                      +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/encodings/idna.py", line 167, in encode                  +
     raise UnicodeError("label too long")                                                                                +
 UnicodeError: label too long                                                                                            +
                                                                                                                         +
 The above exception was the direct cause of the following exception:                                                    +
                                                                                                                         +
 Traceback (most recent call last):                                                                                      +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/request/request.py", line 63, in __repr__ +
     path_query = str(uri.path)                                                                                          +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/furl/furl.py", line 536, in __str__        +
     if self.isabsolute:                                                                                                 +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/furl/furl.py", line 489, in isabsolute     +
     if self._force_absolute(self):                                                                                      +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/furl/furl.py", line 665, in _force_absolute+
     return bool(path) and self.netloc                                                                                   +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/furl/furl.py", line 1288, in netloc        +
     netloc = idna_encode(self.host) or ''                                                                               +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/furl/furl.py", line 101, in idna_encode    +
     return str(o.encode('idna').decode('utf8'))                                                                         +
 UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)                                          +
 ```

1873:

```
-----------------------------------------------------------------------------------------------------------------------------------------
 multiprocessing.pool.RemoteTraceback:                                                                                                  +
 """                                                                                                                                    +
 Traceback (most recent call last):                                                                                                     +
   File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker                                                               +
     result = (True, func(*args, **kwds))                                                                                               +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/__init__.py", line 114, in _parallel_get_web_store       +
     response = ua.get_follow_http_html_redirects(url=scheduled_url.url)                                                                +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/__init__.py", line 400, in get_follow_http_html_redirects+
     response = self.get(url)                                                                                                           +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/__init__.py", line 254, in get                           +
     return self.request(request)                                                                                                       +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/__init__.py", line 761, in request                       +
     content_length = int(content_length)                                                                                               +
 ValueError: invalid literal for int() with base 10: '5843, 5843'                                                                       +
 """                                                                                                                                    +
                                                                                                                                        +
 The above exception was the direct cause of the following exception:                                                                   +
                                                                                                                                        +
 Traceback (most recent call last):                                                                                                     +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/__init__.py", line 528, in parallel_get                  +
     responses = result.get()                                                                                                           +
   File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get                                                                  +
     raise self._value                                                                                                                  +
 ValueError: invalid literal for int() with base 10: '5843, 5843'                                                                       +
```

**Comment by hroberts** [comment]
Two new, different errors in 1905 and 1919.

[foo.txt](https://github.com/berkmancenter/mediacloud/files/1524754/foo.txt)

**Comment by pypt** [comment]
Proactively iterating on this one.

**Comment by pypt** [comment]
Fixed OOM error for topic 1905, added `is_http_url()` calls before every `parallel_get()`, restarted spidering affected topics.

**Comment by pypt** [comment]
Closing as duplicate of #224.
