### ISSUE TITLE
Topic 1896 fails with "AttributeError: 'NoneType' object has no attribute 'readline'"

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#247]
```
-----------------------------------------------------------------------------------------------------------------------------------------
 multiprocessing.pool.RemoteTraceback:                                                                                                  +
 """                                                                                                                                    +
 Traceback (most recent call last):                                                                                                     +
   File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker                                                               +
     result = (True, func(*args, **kwds))                                                                                               +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/__init__.py", line 116, in _parallel_get_web_store       +
     response = ua.get_follow_http_html_redirects(url=scheduled_url.url)                                                                +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/__init__.py", line 402, in get_follow_http_html_redirects+
     response = self.get(url)                                                                                                           +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/__init__.py", line 256, in get                           +
     return self.request(request)                                                                                                       +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/__init__.py", line 943, in request                       +
     previous_response = Response.from_requests_response(requests_response=previous_rq_response)                                        +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/response/response.py", line 56, in from_requests_response+
     data = requests_response.text                                                                                                      +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/requests/models.py", line 847, in text                    +
     if not self.content:                                                                                                               +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/requests/models.py", line 823, in content                 +
     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()                                                     +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/requests/models.py", line 745, in generate                +
     for chunk in self.raw.stream(chunk_size, decode_content=True):                                                                     +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/urllib3/response.py", line 432, in stream                 +
     for line in self.read_chunked(amt, decode_content=decode_content):                                                                 +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/urllib3/response.py", line 598, in read_chunked           +
     self._update_chunk_length()                                                                                                        +
   File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/urllib3/response.py", line 540, in _update_chunk_length   +
     line = self._fp.fp.readline()                                                                                                      +
 AttributeError: 'NoneType' object has no attribute 'readline'                                                                          +
 """                                                                                                                                    +
                                                                                                                                        +
 The above exception was the direct cause of the following exception:                                                                   +
                                                                                                                                        +
 Traceback (most recent call last):                                                                                                     +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/web/user_agent/__init__.py", line 530, in parallel_get                  +
     responses = result.get()                                                                                                           +
   File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get                                                                  +
     raise self._value                                                                                                                  +
 AttributeError: 'NoneType' object has no attribute 'readline'                                                                          +
 
```

**Comment by pypt** [comment]
Started respidering topic 1896.

**Comment by pypt** [comment]
...and topic 1869 too.

**Comment by pypt** [comment]
Both fixed and seem to work now.
