### ISSUE TITLE
python date guesser crash

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#272]
Date guessing crashes on the python side with the below error.  Content is from the below url and is attached.  This is blocking a topic we're trying to run for RWJ, so it would be great to get it fixed ASAP.

https://web.archive.org/web/20150326221558/http://www.theglobeandmail.com/news/world/saudi-arabia-has-150000-troops-for-yemen-operation-report/article23628188/

[foo.txt](https://github.com/berkmancenter/mediacloud/files/1670061/foo.txt)

Traceback (most recent call last):
  File "/home/hroberts/mediacloud/mediacloud/mediawords/tm/guess_date.py", line 62, in guess_date
    guess = mit_guess_date(url=url, html=html)
  File "/home/hroberts/.virtualenvs/mediacloud/lib/python3.5/site-packages/date_guesser/guess_date.py", line 26, in guess_date
    return DateGuesser().guess_date(url, html)
  File "/home/hroberts/.virtualenvs/mediacloud/lib/python3.5/site-packages/date_guesser/guess_date.py", line 91, in guess_date
    new_date, new_accuracy = self.parser.parse(date_string)
  File "/home/hroberts/.virtualenvs/mediacloud/lib/python3.5/site-packages/date_guesser/dates.py", line 65, in parse
    for new_date, new_accuracy in self.iter_matches(date_string, fmts=fmts):
  File "/home/hroberts/.virtualenvs/mediacloud/lib/python3.5/site-packages/date_guesser/dates.py", line 48, in iter_matches
    yield self._try_format(date_string, date_format)
  File "/home/hroberts/.virtualenvs/mediacloud/lib/python3.5/site-packages/date_guesser/dates.py", line 35, in _try_format
    parsed_date = self.parser.parse(date_string, fmt=date_format.format)
  File "/home/hroberts/.virtualenvs/mediacloud/lib/python3.5/site-packages/arrow/parser.py", line 183, in parse
    return self._build_datetime(parts)
  File "/home/hroberts/.virtualenvs/mediacloud/lib/python3.5/site-packages/arrow/parser.py", line 269, in _build_datetime
    tzinfo=parts.get('tzinfo'))
ValueError: month must be in 1..12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hroberts/mediacloud/script/benchmark_date_guessing.py", line 28, in <module>
    main()
  File "/home/hroberts/mediacloud/script/benchmark_date_guessing.py", line 24, in main
    html=content
  File "/home/hroberts/mediacloud/mediacloud/mediawords/tm/guess_date.py", line 64, in guess_date
    raise McGuessDateException("Guess date failed: %s" % str(ex))
mediawords.tm.guess_date.McGuessDateException: Guess date failed: month must be in 1..12

**Comment by hroberts** [comment]
and another one just now:

message
"Date guesser died while guessing date for URL https://www.kenyans.co.ke/news/22189-details-audit-report-iebc-servers-and-election-forms-presidential-petition-parties: Traceback (most recent call last):
  File ""/home/mediacloud/mediacloud/mediacloud/mediawords/tm/guess_date.py"", line 62, in guess_date
    guess = mit_guess_date(url=url, html=html)
  File ""/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/date_guesser/guess_date.py"", line 24, in guess_date
    return DateGuesser().guess_date(url, html)
  File ""/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/date_guesser/guess_date.py"", line 87, in guess_date
    new_date, new_accuracy = self.parser.parse(date_string)
  File ""/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/date_guesser/dates.py"", line 65, in parse
    for new_date, new_accuracy in self.iter_matches(date_string, fmts=fmts):
  File ""/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/date_guesser/dates.py"", line 48, in iter_matches
    yield self._try_format(date_string, date_format)
  File ""/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/date_guesser/dates.py"", line 35, in _try_format
    parsed_date = self.parser.parse(date_string, fmt=date_format.format)
  File ""/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/arrow/parser.py"", line 183, in parse
    return self._build_datetime(parts)
  File ""/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/arrow/parser.py"", line 269, in _build_datetime
    tzinfo=parts.get('tzinfo'))
ValueError: year is out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/mediacloud/mediacloud/mediacloud/mediawords/tm/guess_date.py"", line 64, in guess_date
    raise McGuessDateException(""Guess date failed: %s"" % str(ex))
mediawords.tm.guess_date.McGuessDateException: Guess date failed: year is out of range
 at (eval 1009) line 3.
	MediaWords::TM::GuessDate::PythonProxy::guess_date(undef, ""mediawords.tm.guess_date"", ""guess_date"", ""https://www.kenyans.co.ke/news/22189-details-audit-report-ieb""..., ""<!DOCTYPE html>\x{d}\x{a}<html lang=\""en\"" dir=\""ltr\"">\x{d}\x{a}\x{d}\x{a}<head>\x{d}\x{a}  <met""...) called at lib/MediaWords/TM/GuessDate.pm line 32
	eval {...} called at lib/MediaWords/TM/GuessDate.pm line 32
	MediaWords::TM::GuessDate::guess_date(""https://www.kenyans.co.ke/news/22189-details-audit-report-ieb""..., ""<!DOCTYPE html>\x{d}\x{a}<html lang=\""en\"" dir=\""ltr\"">\x{d}\x{a}\x{d}\x{a}<head>\x{d}\x{a}  <met""...) called at lib/MediaWords/TM/Mine.pm line 713
	MediaWords::TM::Mine::get_new_story_date(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x23514f10), ""<!DOCTYPE html>\x{d}\x{a}<html lang=\""en\"" dir=\""ltr\"">\x{d}\x{a}\x{d}\x{a}<head>\x{d}\x{a}  <met""..., HASH(0x23531ba8), HASH(0x4cb1ab98)) called at lib/MediaWords/TM/Mine.pm line 807
	MediaWords::TM::Mine::generate_new_story_hash(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), ""<!DOCTYPE html>\x{d}\x{a}<html lang=\""en\"" dir=\""ltr\"">\x{d}\x{a}\x{d}\x{a}<head>\x{d}\x{a}  <met""..., HASH(0x23531ba8), HASH(0x4cb1ab98), HASH(0x23846f20)) called at lib/MediaWords/TM/Mine.pm line 951
	MediaWords::TM::Mine::add_new_story(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x4cb1ab98), undef, HASH(0x391e000), 0, 1, 1) called at lib/MediaWords/TM/Mine.pm line 1533
	MediaWords::TM::Mine::get_stories_to_extract(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), ARRAY(0x4d1911d8)) called at lib/MediaWords/TM/Mine.pm line 1621
	MediaWords::TM::Mine::add_new_links_chunk(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), 2, ARRAY(0x29bd9380)) called at lib/MediaWords/TM/Mine.pm line 1673
	MediaWords::TM::Mine::add_new_links(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), 2, ARRAY(0x94d6378)) called at lib/MediaWords/TM/Mine.pm line 1698
	MediaWords::TM::Mine::spider_new_links(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), 2) called at lib/MediaWords/TM/Mine.pm line 1738
	MediaWords::TM::Mine::run_spider(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000)) called at lib/MediaWords/TM/Mine.pm line 2706
	MediaWords::TM::Mine::do_mine_topic(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000)) called at lib/MediaWords/TM/Mine.pm line 2863
	eval {...} called at lib/MediaWords/TM/Mine.pm line 2862
	MediaWords::TM::Mine::mine_topic(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), HASH(0x33b8c50)) called at lib/MediaWords/Job/TM/MineTopic.pm line 74
	MediaWords::Job::TM::MineTopic::run_statefully(MediaWords::Job::TM::MineTopic=HASH(0x87e85f0), MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x88e9c60)) called at lib/MediaWords/AbstractJob.pm line 312
	eval {...} called at lib/MediaWords/AbstractJob.pm line 296
	MediaWords::AbstractJob::run(MediaWords::Job::TM::MineTopic=HASH(0x87e85f0), HASH(0x88e9c60)) called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 358
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 349
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 321
	MediaCloud::JobManager::Job::run_locally(""MediaWords::Job::TM::MineTopic"", HASH(0x88e9c60), ""150e4349-f591-45e1-b250-e2613c8ce87f"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 464
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 464
	MediaCloud::JobManager::Broker::RabbitMQ::_process_worker_message(MediaCloud::JobManager::Broker::RabbitMQ=HASH(0x88e9978), ""MediaWords::Job::TM::MineTopic"", HASH(0x88e9888)) called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 551
	MediaCloud::JobManager::Broker::RabbitMQ::start_worker(MediaCloud::JobManager::Broker::RabbitMQ=HASH(0x88e9978), ""MediaWords::Job::TM::MineTopic"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Worker.pm line 63
	MediaCloud::JobManager::Worker::start_worker(""lib/MediaWords/Job/TM/MineTopic.pm"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/bin/mjm_worker.pl line 49
	main::main() called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/bin/mjm_worker.pl line 52
 at lib/MediaWords/CommonLibs.pm line 96.
	MediaWords::CommonLibs::LOGCONFESS(""Date guesser died while guessing date for URL https://www.ken""...) called at lib/MediaWords/TM/GuessDate.pm line 33
	MediaWords::TM::GuessDate::guess_date(""https://www.kenyans.co.ke/news/22189-details-audit-report-ieb""..., ""<!DOCTYPE html>\x{d}\x{a}<html lang=\""en\"" dir=\""ltr\"">\x{d}\x{a}\x{d}\x{a}<head>\x{d}\x{a}  <met""...) called at lib/MediaWords/TM/Mine.pm line 713
	MediaWords::TM::Mine::get_new_story_date(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x23514f10), ""<!DOCTYPE html>\x{d}\x{a}<html lang=\""en\"" dir=\""ltr\"">\x{d}\x{a}\x{d}\x{a}<head>\x{d}\x{a}  <met""..., HASH(0x23531ba8), HASH(0x4cb1ab98)) called at lib/MediaWords/TM/Mine.pm line 807
	MediaWords::TM::Mine::generate_new_story_hash(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), ""<!DOCTYPE html>\x{d}\x{a}<html lang=\""en\"" dir=\""ltr\"">\x{d}\x{a}\x{d}\x{a}<head>\x{d}\x{a}  <met""..., HASH(0x23531ba8), HASH(0x4cb1ab98), HASH(0x23846f20)) called at lib/MediaWords/TM/Mine.pm line 951
	MediaWords::TM::Mine::add_new_story(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x4cb1ab98), undef, HASH(0x391e000), 0, 1, 1) called at lib/MediaWords/TM/Mine.pm line 1533
	MediaWords::TM::Mine::get_stories_to_extract(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), ARRAY(0x4d1911d8)) called at lib/MediaWords/TM/Mine.pm line 1621
	MediaWords::TM::Mine::add_new_links_chunk(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), 2, ARRAY(0x29bd9380)) called at lib/MediaWords/TM/Mine.pm line 1673
	MediaWords::TM::Mine::add_new_links(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), 2, ARRAY(0x94d6378)) called at lib/MediaWords/TM/Mine.pm line 1698
	MediaWords::TM::Mine::spider_new_links(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), 2) called at lib/MediaWords/TM/Mine.pm line 1738
	MediaWords::TM::Mine::run_spider(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000)) called at lib/MediaWords/TM/Mine.pm line 2706
	MediaWords::TM::Mine::do_mine_topic(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000)) called at lib/MediaWords/TM/Mine.pm line 2863
	eval {...} called at lib/MediaWords/TM/Mine.pm line 2862
	MediaWords::TM::Mine::mine_topic(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), HASH(0x33b8c50)) called at lib/MediaWords/Job/TM/MineTopic.pm line 74
	MediaWords::Job::TM::MineTopic::run_statefully(MediaWords::Job::TM::MineTopic=HASH(0x87e85f0), MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x88e9c60)) called at lib/MediaWords/AbstractJob.pm line 312
	eval {...} called at lib/MediaWords/AbstractJob.pm line 296
	MediaWords::AbstractJob::run(MediaWords::Job::TM::MineTopic=HASH(0x87e85f0), HASH(0x88e9c60)) called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 358
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 349
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 321
	MediaCloud::JobManager::Job::run_locally(""MediaWords::Job::TM::MineTopic"", HASH(0x88e9c60), ""150e4349-f591-45e1-b250-e2613c8ce87f"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 464
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 464
	MediaCloud::JobManager::Broker::RabbitMQ::_process_worker_message(MediaCloud::JobManager::Broker::RabbitMQ=HASH(0x88e9978), ""MediaWords::Job::TM::MineTopic"", HASH(0x88e9888)) called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 551
	MediaCloud::JobManager::Broker::RabbitMQ::start_worker(MediaCloud::JobManager::Broker::RabbitMQ=HASH(0x88e9978), ""MediaWords::Job::TM::MineTopic"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Worker.pm line 63
	MediaCloud::JobManager::Worker::start_worker(""lib/MediaWords/Job/TM/MineTopic.pm"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/bin/mjm_worker.pl line 49
	main::main() called at lib/MediaWords/CommonLibs.pm line 96.
	MediaWords::CommonLibs::LOGCONFESS(""Date guesser died while guessing date for URL https://www.ken""...) called at lib/MediaWords/TM/GuessDate.pm line 33
	MediaWords::TM::GuessDate::guess_date(""https://www.kenyans.co.ke/news/22189-details-audit-report-ieb""..., ""<!DOCTYPE html>\x{d}\x{a}<html lang=\""en\"" dir=\""ltr\"">\x{d}\x{a}\x{d}\x{a}<head>\x{d}\x{a}  <met""...) called at lib/MediaWords/TM/Mine.pm line 713
	MediaWords::TM::Mine::get_new_story_date(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x23514f10), ""<!DOCTYPE html>\x{d}\x{a}<html lang=\""en\"" dir=\""ltr\"">\x{d}\x{a}\x{d}\x{a}<head>\x{d}\x{a}  <met""..., HASH(0x23531ba8), HASH(0x4cb1ab98)) called at lib/MediaWords/TM/Mine.pm line 807
	MediaWords::TM::Mine::generate_new_story_hash(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), ""<!DOCTYPE html>\x{d}\x{a}<html lang=\""en\"" dir=\""ltr\"">\x{d}\x{a}\x{d}\x{a}<head>\x{d}\x{a}  <met""..., HASH(0x23531ba8), HASH(0x4cb1ab98), HASH(0x23846f20)) called at lib/MediaWords/TM/Mine.pm line 951
	MediaWords::TM::Mine::add_new_story(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x4cb1ab98), undef, HASH(0x391e000), 0, 1, 1) called at lib/MediaWords/TM/Mine.pm line 1533
	MediaWords::TM::Mine::get_stories_to_extract(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), ARRAY(0x4d1911d8)) called at lib/MediaWords/TM/Mine.pm line 1621
	MediaWords::TM::Mine::add_new_links_chunk(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), 2, ARRAY(0x29bd9380)) called at lib/MediaWords/TM/Mine.pm line 1673
	MediaWords::TM::Mine::add_new_links(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), 2, ARRAY(0x94d6378)) called at lib/MediaWords/TM/Mine.pm line 1698
	MediaWords::TM::Mine::spider_new_links(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), 2) called at lib/MediaWords/TM/Mine.pm line 1738
	MediaWords::TM::Mine::run_spider(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000)) called at lib/MediaWords/TM/Mine.pm line 2706
	MediaWords::TM::Mine::do_mine_topic(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000)) called at lib/MediaWords/TM/Mine.pm line 2863
	eval {...} called at lib/MediaWords/TM/Mine.pm line 2862
	MediaWords::TM::Mine::mine_topic(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), HASH(0x33b8c50)) called at lib/MediaWords/Job/TM/MineTopic.pm line 74
	MediaWords::Job::TM::MineTopic::run_statefully(MediaWords::Job::TM::MineTopic=HASH(0x87e85f0), MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x88e9c60)) called at lib/MediaWords/AbstractJob.pm line 312
	eval {...} called at lib/MediaWords/AbstractJob.pm line 296
	MediaWords::AbstractJob::run(MediaWords::Job::TM::MineTopic=HASH(0x87e85f0), HASH(0x88e9c60)) called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 358
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 349
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 321
	MediaCloud::JobManager::Job::run_locally(""MediaWords::Job::TM::MineTopic"", HASH(0x88e9c60), ""150e4349-f591-45e1-b250-e2613c8ce87f"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 464
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 464
	MediaCloud::JobManager::Broker::RabbitMQ::_process_worker_message(MediaCloud::JobManager::Broker::RabbitMQ=HASH(0x88e9978), ""MediaWords::Job::TM::MineTopic"", HASH(0x88e9888)) called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 551
	MediaCloud::JobManager::Broker::RabbitMQ::start_worker(MediaCloud::JobManager::Broker::RabbitMQ=HASH(0x88e9978), ""MediaWords::Job::TM::MineTopic"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Worker.pm line 63
	MediaCloud::JobManager::Worker::start_worker(""lib/MediaWords/Job/TM/MineTopic.pm"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/bin/mjm_worker.pl line 49
	main::main() called at lib/MediaWords/CommonLibs.pm line 91.
	MediaWords::CommonLibs::LOGDIE(""Date guesser died while guessing date for URL https://www.ken""...) called at lib/MediaWords/TM/Mine.pm line 2870
	MediaWords::TM::Mine::mine_topic(MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x391e000), HASH(0x33b8c50)) called at lib/MediaWords/Job/TM/MineTopic.pm line 74
	MediaWords::Job::TM::MineTopic::run_statefully(MediaWords::Job::TM::MineTopic=HASH(0x87e85f0), MediaWords::DB::HandlerProxy=HASH(0x88e98d0), HASH(0x88e9c60)) called at lib/MediaWords/AbstractJob.pm line 312
	eval {...} called at lib/MediaWords/AbstractJob.pm line 296
	MediaWords::AbstractJob::run(MediaWords::Job::TM::MineTopic=HASH(0x87e85f0), HASH(0x88e9c60)) called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 358
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 349
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Job.pm line 321
	MediaCloud::JobManager::Job::run_locally(""MediaWords::Job::TM::MineTopic"", HASH(0x88e9c60), ""150e4349-f591-45e1-b250-e2613c8ce87f"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 464
	eval {...} called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 464
	MediaCloud::JobManager::Broker::RabbitMQ::_process_worker_message(MediaCloud::JobManager::Broker::RabbitMQ=HASH(0x88e9978), ""MediaWords::Job::TM::MineTopic"", HASH(0x88e9888)) called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Broker/RabbitMQ.pm line 551
	MediaCloud::JobManager::Broker::RabbitMQ::start_worker(MediaCloud::JobManager::Broker::RabbitMQ=HASH(0x88e9978), ""MediaWords::Job::TM::MineTopic"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/lib/perl5/MediaCloud/JobManager/Worker.pm line 63
	MediaCloud::JobManager::Worker::start_worker(""lib/MediaWords/Job/TM/MineTopic.pm"") called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/bin/mjm_worker.pl line 49
	main::main() called at /home/mediacloud/.perlbrew/libs/perl-system@mediacloud/bin/mjm_worker.pl line 52
"
