### ISSUE TITLE
Topic 2063 fails with UnicodeEncodeError

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#310]
```
 UnicodeEncodeError: 'utf-8' codec can't encode character '\udd7a' in position 4259: surrogates not allowed             +
                                                                                                                        +
 During handling of the above exception, another exception occurred:                                                    +
                                                                                                                        +
 Traceback (most recent call last):                                                                                     +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/db/handler.py", line 508, in create                          +
     table = decode_object_from_bytes_if_needed(table)                                                                  +
   File "/home/mediacloud/mediacloud/mediacloud/mediawords/util/perl.py", line 22, in decode_object_from_bytes_if_needed+
     def __decode_string_from_bytes_if_needed(string: Union[int, str, bytes, None]) -> Union[int, str, None]:           +
   File "/usr/lib/python3.5/typing.py", line 549, in __getitem__                                                        +
     if not isinstance(parameters, tuple):                                                                              +
 SystemError: <built-in function isinstance> returned a result with an error set                                        +
```

No idea what's happening here and what codepath does it come from.

**Comment by hroberts** [comment]
I believe these unicode errors are all fixed by moving the link fetching to python.  closing this until we see the errors pop up with the new system.
