### ISSUE TITLE
wc/list queries don't appear to work when in "quotes" and in Hindi

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#666]
Can't explain that!

```
$ curl -v "https://api.mediacloud.org/api/v2/wc/list?q=%28%22%E0%A4%AE%E0%A5%8B%E0%A4%A6%E0%A5%80%22%29+AND+%28%28+tags_id_media%3A%2834412118+38379954%29%29%29&num_words=100&sample_size=1000&include_stopwords=0&include_stats=0&ngram_size=1&fq=publish_day%3A%5B2020-01-01T00%3A00%3A00Z+TO+2020-02-18T00%3A00%3A00Z%5D&key=<...>"
*   Trying 18.27.195.14...
* TCP_NODELAY set
* Connected to api.mediacloud.org (18.27.195.14) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=mediacloud.org
*  start date: Dec 19 15:10:34 2019 GMT
*  expire date: Mar 18 15:10:34 2020 GMT
*  subjectAltName: host "api.mediacloud.org" matched cert's "*.mediacloud.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f9a3b807400)
> GET /api/v2/wc/list?q=%28%22%E0%A4%AE%E0%A5%8B%E0%A4%A6%E0%A5%80%22%29+AND+%28%28+tags_id_media%3A%2834412118+38379954%29%29%29&num_words=100&sample_size=1000&include_stopwords=0&include_stats=0&ngram_size=1&fq=publish_day%3A%5B2020-01-01T00%3A00%3A00Z+TO+2020-02-18T00%3A00%3A00Z%5D&key=<...> HTTP/2
> Host: api.mediacloud.org
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 502 
< server: nginx
< date: Tue, 18 Feb 2020 23:32:43 GMT
< content-type: text/html
< content-length: 166
< 
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host api.mediacloud.org left intact
* Closing connection 0
```

Weird bits:

* Other UTF-8 queries, e.g. Lithuanian, work fine;
* Hindi queries without quotes work fine;
* After making a query, I can't see its entry in Nginx log, so either it dies really silently, or it's Nginx that decides that the request is not worthy to reach Perl API workers.

Encoded value of `q`:

```
%28%22%E0%A4%AE%E0%A5%8B%E0%A4%A6%E0%A5%80%22%29+AND+%28%28+tags_id_media%3A%2834412118+38379954%29%29%29
```

is the following:

```
("मोदी")+AND+((+tags_id_media:(34412118+38379954)))
```

**Comment by pypt** [comment]
I think this has something to do spaces being encoded to literal plus signs instead of `%2B` in the `q` parameter or something like that.

**Comment by pypt** [comment]
Found it in Nginx's own log:

```
2020/02/20 13:20:15 [error] 6#6: *2198 FastCGI sent in stderr: "[error] Caught exception in MediaWords::Controller::Api::V2::Wc->list_GET "Traceback (most recent call last):
  File "/opt/mediacloud/src/common/python/mediawords/db/result/result.py", line 77, in __execute
    cursor.execute(*query_args)
  File "/usr/local/lib/python3.7/dist-packages/psycopg2/extras.py", line 141, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.DataError: invalid regular expression: invalid escape \ sequence
During handling of the above exception, anot" while reading response header from upstream, client: 10.1.1.67, server: _, request: "GET /api/v2/wc/list?q=%28%22%E0%A4%AE%E0%A5%8B%E0%A4%A6%E0%A5%80%22%29+AND+%28%28+tags_id_media%3A%2834412118+38379954%29%29%29&num_words=100&sample_size=1000&include_stopwords=0&include_stats=0&ngram_size=1&fq=publish_day%3A%5B2020-01-01T00%3A00%3A00Z+TO+2020-02-18T00%3A00%3A00Z%5D&key=<...> HTTP/1.1", upstream: "fastcgi://10.1.1.152:9090", host: "api.mediacloud.org"
2020/02/20 13:20:15 [error] 6#6: *2198 FastCGI sent in stderr: "her exception occurred:
Traceback (most recent call last):
  File "/opt/mediacloud/src/common/python/mediawords/db/handler.py", line 201, in query
    print_warnings=self.__print_warnings)
  File "/opt/mediacloud/src/common/python/mediawords/db/result/result.py", line 35, in __init__
    print_warnings=print_warnings)
  File "/opt/mediacloud/src/common/python/mediawords/db/result/result.py", line 115, in __execute
    'mogrified_query': str(mogrified_query),
mediawords.db.exceptions.result.McDataba" while reading response header from upstream, client: 10.1.1.67, server: _, request: "GET /api/v2/wc/list?q=%28%22%E0%A4%AE%E0%A5%8B%E0%A4%A6%E0%A5%80%22%29+AND+%28%28+tags_id_media%3A%2834412118+38379954%29%29%29&num_words=100&sample_size=1000&include_stopwords=0&include_stats=0&ngram_size=1&fq=publish_day%3A%5B2020-01-01T00%3A00%3A00Z+TO+2020-02-18T00%3A00%3A00Z%5D&key=<...> HTTP/1.1", upstream: "fastcgi://10.1.1.152:9090", host: "api.mediacloud.org"
2020/02/20 13:20:15 [error] 6#6: *2198 FastCGI sent in stderr: "seResultException: Query failed: invalid regular expression: invalid escape \ sequence
; query: ("select\n        ss.sentence,\n        ss.media_id,\n        ss.publish_date,\n        ss.sentence_number,\n        ss.stories_id,\n        ss.story_sentences_id,\n        ss.language,\n        s.language story_language\n    from\n        story_sentences ss\n        join stories s using ( stories_id )\n        join _tmp_ids_hgb1l9GWRTjh0ZKn ids on ( s.stories_id = ids.id )\n    where\n        sentence ~" while reading response header from upstream, client: 10.1.1.67, server: _, request: "GET /api/v2/wc/list?q=%28%22%E0%A4%AE%E0%A5%8B%E0%A4%A6%E0%A5%80%22%29+AND+%28%28+tags_id_media%3A%2834412118+38379954%29%29%29&num_words=100&sample_size=1000&include_stopwords=0&include_stats=0&ngram_size=1&fq=publish_day%3A%5B2020-01-01T00%3A00%3A00Z+TO+2020-02-18T00%3A00%3A00Z%5D&key=<...> HTTP/1.1", upstream: "fastcgi://10.1.1.152:9090", host: "api.mediacloud.org"
2020/02/20 13:20:15 [error] 6#6: *2198 FastCGI sent in stderr: "'(?isx)(?: (?: (?:^|\\W)म\\\\\\ोद\\\\\\ी ) )' \n   order by random() limit 1000 \n", {}); mogrified query: b"select\n        ss.sentence,\n        ss.media_id,\n        ss.publish_date,\n        ss.sentence_number,\n        ss.stories_id,\n        ss.story_sentences_id,\n        ss.language,\n        s.language story_language\n    from\n        story_sentences ss\n        join stories s using ( stories_id )\n        join _tmp_ids_hgb1l9GWRTjh0ZKn ids on ( s.stories_id = ids.id )\n    where\n" while reading response header from upstream, client: 10.1.1.67, server: _, request: "GET /api/v2/wc/list?q=%28%22%E0%A4%AE%E0%A5%8B%E0%A4%A6%E0%A5%80%22%29+AND+%28%28+tags_id_media%3A%2834412118+38379954%29%29%29&num_words=100&sample_size=1000&include_stopwords=0&include_stats=0&ngram_size=1&fq=publish_day%3A%5B2020-01-01T00%3A00%3A00Z+TO+2020-02-18T00%3A00%3A00Z%5D&key=<...> HTTP/1.1", upstream: "fastcgi://10.1.1.152:9090", host: "api.mediacloud.org"
2020/02/20 13:20:15 [error] 6#6: *2198 FastCGI sent in stderr: "        sentence ~ '(?isx)(?: (?: (?:^|\\W)\xe0\xa4\xae\\\\\\\xe0\xa5\x8b\xe0\xa4\xa6\\\\\\\xe0\xa5\x80 ) )' \n   order by random() limit 1000 \n""
[error] Caught exception in engine "Body must be bytes and should not contain wide characters (UTF-8 strings) at /usr/local/share/perl/5.22.1/Plack/Middleware/Lint.pm line 156."" while reading response header from upstream, client: 10.1.1.67, server: _, request: "GET /api/v2/wc/list?q=%28%22%E0%A4%AE%E0%A5%8B%E0%A4%A6%E0%A5%80%22%29+AND+%28%28+tags_id_media%3A%2834412118+38379954%29%29%29&num_words=100&sample_size=1000&include_stopwords=0&include_stats=0&ngram_size=1&fq=publish_day%3A%5B2020-01-01T00%3A00%3A00Z+TO+2020-02-18T00%3A00%3A00Z%5D&key=<...> HTTP/1.1", upstream: "fastcgi://10.1.1.152:9090", host: "api.mediacloud.org"
2020/02/20 13:20:15 [error] 6#6: *2198 upstream prematurely closed FastCGI stdout while reading response header from upstream, client: 10.1.1.67, server: _, request: "GET /api/v2/wc/list?q=%28%22%E0%A4%AE%E0%A5%8B%E0%A4%A6%E0%A5%80%22%29+AND+%28%28+tags_id_media%3A%2834412118+38379954%29%29%29&num_words=100&sample_size=1000&include_stopwords=0&include_stats=0&ngram_size=1&fq=publish_day%3A%5B2020-01-01T00%3A00%3A00Z+TO+2020-02-18T00%3A00%3A00Z%5D&key=<...> HTTP/1.1", upstream: "fastcgi://10.1.1.152:9090", host: "api.mediacloud.org"
```

**Comment by pypt** [comment]
@hroberts, I don't think our Solr query parser (`apps/webapp-api/src/python/webapp/solr/query/parse.py`) is able to figure out word boundaries for non-English (Hindi) text. Any advice/insights?

**Comment by pypt** [comment]
Appears to be working now:

```
$ curl -v "https://api.mediacloud.org/api/v2/wc/list?q=%28%22%E0%A4%AE%E0%A5%8B%E0%A4%A6%E0%A5%80%22%29+AND+%28%28+tags_id_media%3A%2834412118+38379954%29%29%29&num_words=100&sample_size=1000&include_stopwords=0&include_stats=0&ngram_size=1&fq=publish_day%3A%5B2020-01-01T00%3A00%3A00Z+TO+2020-02-18T00%3A00%3A00Z%5D&key=<...>"
*   Trying 18.27.195.14...
* TCP_NODELAY set
* Connected to api.mediacloud.org (18.27.195.14) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=mediacloud.org
*  start date: Dec 19 15:10:34 2019 GMT
*  expire date: Mar 18 15:10:34 2020 GMT
*  subjectAltName: host "api.mediacloud.org" matched cert's "*.mediacloud.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fb2c0807e00)
> GET /api/v2/wc/list?q=%28%22%E0%A4%AE%E0%A5%8B%E0%A4%A6%E0%A5%80%22%29+AND+%28%28+tags_id_media%3A%2834412118+38379954%29%29%29&num_words=100&sample_size=1000&include_stopwords=0&include_stats=0&ngram_size=1&fq=publish_day%3A%5B2020-01-01T00%3A00%3A00Z+TO+2020-02-18T00%3A00%3A00Z%5D&key=<...> HTTP/2
> Host: api.mediacloud.org
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: nginx
< date: Tue, 25 Feb 2020 17:58:56 GMT
< content-type: application/json; charset=UTF-8
< content-length: 5683
< vary: Accept-Encoding
< vary: Accept-Encoding
< vary: Content-Type
< access-control-allow-origin: *
< 
[{"count":937,"stem":"मोदी","term":"मोदी"},{"count":294,"stem":"प्रधानमंत्री","term":"प्रधानमंत्री"},{"count":284,"stem":"नरेंद्र","term":"नरेंद्र"},{"count":245,"stem":"सरकार","term":"सरकार"},{"count":191,"stem":"द","term":"द"},{"count":172,"stem":"म","term":"म"},{"count":168,"stem":"पीएम","term":"पीएम"},{"count":164,"stem":"य","term":"य"},{"count":155,"stem":"न","term":"न"},{"count":154,"stem":"त","term":"त"},{"count":152,"stem":"र","term":"र"},{"count":138,"stem":"क","term":"क"},{"count":136,"stem":"ल","term":"ल"},{"count":114,"stem":"च","term":"च"},{"count":95,"stem":"देश","term":"देश"},{"count":86,"stem":"प","term":"प"},{"count":83,"stem":"व","term":"व"},{"count":82,"stem":"स","term":"स"},{"count":76,"stem":"ह","term":"ह"},{"count":76,"stem":"शाह","term":"शाह"},{"count":61,"stem":"मंत्री","term":"मंत्री"},{"count":61,"stem":"उन्होंने","term":"उन्होंने"},{"count":55,"stem":"सिंह","term":"सिंह"},{"count":55,"stem":"बता","term":"बताया"},{"count":55,"stem":"दिल्ली","term":"दिल्ली"},{"count":55,"stem":"कुमार","term":"कुमार"},{"count":53,"stem":"अमित","term":"अमित"},{"count":49,"stem":"ट","term":"ट"},{"count":49,"stem":"कान","term":"कानून"},{"count":49,"stem":"करे","term":"करेंगे"},{"count":48,"stem":"भाजपा","term":"भाजपा"},{"count":48,"stem":"कार्यक्रम","term":"कार्यक्रम"},{"count":45,"stem":"सीएए","term":"सीएए"},{"count":45,"stem":"रही","term":"रही"},{"count":45,"stem":"नरेन्द्र","term":"नरेन्द्र"},{"count":44,"stem":"भारत","term":"भारत"},{"count":44,"stem":"दौर","term":"दौरान"},{"count":44,"stem":"चर्चा","term":"चर्चा"},{"count":42,"stem":"श","term":"श"},{"count":42,"stem":"कांग्रेस","term":"कांग्रेस"},{"count":40,"stem":"खिला","term":"खिलाफ"},{"count":39,"stem":"सुशील","term":"सुशील"},{"count":39,"stem":"नागरिकता","term":"नागरिकता"},{"count":38,"stem":"लोगों","term":"लोगों"},{"count":38,"stem":"गृह","term":"गृह"},{"count":37,"stem":"बात","term":"बात"},{"count":36,"stem":"विरोध","term":"विरोध"},{"count":36,"stem":"परीक्षा","term":"परीक्षा"},{"count":36,"stem":"गांधी","term":"गांधी"},{"count":36,"stem":"ग","term":"ग"},{"count":36,"stem":"केंद्र","term":"केंद्र"},{"count":35,"stem":"ष","term":"ष"},{"count":35,"stem":"आह","term":"आह"},{"count":34,"stem":"भ","term":"भ"},{"count":34,"stem":"ज","term":"ज"},{"count":34,"stem":"छात्र","term":"छात्रों"},{"count":32,"stem":"राहुल","term":"राहुल"},{"count":32,"stem":"काम","term":"काम"},{"count":31,"stem":"हमल","term":"हमला"},{"count":31,"stem":"साल","term":"साल"},{"count":31,"stem":"सरक","term":"सरक"},{"count":31,"stem":"ध","term":"ध"},{"count":31,"stem":"देने","term":"देने"},{"count":31,"stem":"दी","term":"दी"},{"count":30,"stem":"कार्य","term":"कार्यकाल"},{"count":29,"stem":"मिल","term":"मिलने"},{"count":29,"stem":"बैठक","term":"बैठक"},{"count":28,"stem":"करोड़","term":"करोड़"},{"count":27,"stem":"शामिल","term":"शामिल"},{"count":27,"stem":"वाराणसी","term":"वाराणसी"},{"count":27,"stem":"पहुंच","term":"पहुंचे"},{"count":27,"stem":"नेता","term":"नेता"},{"count":27,"stem":"चुनाव","term"* Connection #0 to host api.mediacloud.org left intact
:"चुनाव"},{"count":26,"stem":"मुख्यमंत्री","term":"मुख्यमंत्री"},{"count":26,"stem":"बना","term":"बनाने"},{"count":26,"stem":"बजट","term":"बजट"},{"count":26,"stem":"नीति","term":"नीतियों"},{"count":26,"stem":"जनवरी","term":"जनवरी"},{"count":26,"stem":"अध्यक्ष","term":"अध्यक्ष"},{"count":25,"stem":"हूं","term":"हूं"},{"count":25,"stem":"लगा","term":"लगा"},{"count":25,"stem":"राज्य","term":"राज्य"},{"count":25,"stem":"नर","term":"नर"},{"count":25,"stem":"क्षेत्र","term":"क्षेत्र"},{"count":25,"stem":"आरोप","term":"आरोप"},{"count":24,"stem":"नाम","term":"नाम"},{"count":23,"stem":"सवाल","term":"सवाल"},{"count":23,"stem":"रध","term":"रध"},{"count":23,"stem":"बार","term":"बार"},{"count":23,"stem":"बंगाल","term":"बंगाल"},{"count":22,"stem":"राम","term":"राम"},{"count":22,"stem":"मैं","term":"मैं"},{"count":22,"stem":"भारतीय","term":"भारतीय"},{"count":22,"stem":"तप","term":"तप"},{"count":22,"stem":"ट्वीट","term":"ट्वीट"},{"count":22,"stem":"अस","term":"अस"},{"count":22,"stem":"PM","term":"PM"},{"count":21,"stem":"संब","term":"संबोधित"},{"count":21,"stem":"यादव","term":"यादव"},{"count":21,"stem":"मुद्द","term":"मुद्दे"}]* Closing connection 0
```
